name: Deploy Favicon Factory

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create dist folder
      run: mkdir -p dist
    
    - name: Copy files
      run: |
        cp -r *.html *.css *.js *.svg *.png icons/ dist/ 2>/dev/null || true
        echo "Files copied successfully"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
